name: Auto Publish Website
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: isntall git
        run: sudo apt install --yes git
      - name: git global
        run: sudo git config --global --add safe.directory '*'
      - name: set version
        run: sudo git tag v99.99.99-alpha
        
      - name: Fetch all tags
        run: sudo git fetch --force --tags
        
      - name: install sshpass
        run: sudo apt install sshpass --yes
        
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
            network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
            auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: ping host
        shell: bash
        run: |
          count=10
          while ! ping -c 1 10.147.18.11 ; do
            echo "waiting..." ;
            sleep 1 ;
            let count=count-1
          done
          echo "ping success"
      - name: send message
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"CasaOS updated"}}'  https://open.feishu.cn/open-apis/bot/v2/hook/eb8f45c7-9636-4b64-84f2-a66d9aeb9d30
      - name: Error Handling
        if: ${{ failure() }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"test"}}' https://open.feishu.cn/open-apis/bot/v2/hook/eb8f45c7-9636-4b64-84f2-a66d9aeb9d30
